### ISSUE TITLE
Resource ID for Multi-Tenant SharePoint Environment

### ISSUE THREAD

**Issue by dwhofer** [wearearchitect/sharepoint-oauth-app-client#3]
My company uses a MSP that has their own multi-tenant sharepoint 2013 installation. 

I used your debugging tips to set the json param to 'false' in the createFromAOP function in SPAccessToken.php.  With this, I was able to see this detailed error: "ACS90019: Unable to determine the tenant identifier from the request."

Let's say that my SP 2013 site url is: xyz.mycompany.com and I have created the following App Identifier: i:0i.t|ms.sp.ext|61zzzd3f-77zz-4951-aezz-zzzzcc259e9a@bf5225zz-840f-46zz-zz6f-zzzze97710zz' and I have validated this with _layouts/15/appprincipals.aspx?Scope=Web.

In a previous issue, I was instructed to use the value from the APP Identifier after the @ sign.  However, that is not working in this multi-tenant environment.  

The example value in your code is '00000000-0000-ffff-0000-000000000000/example.sharepoint.com@09g7c3b0-f0d4-416d-39a7-09671ab91f64' which makes me think that I need to somehow combine my App Identfier with the url somehow.

**Comment by quetzyg** [comment]
Yes, the `resource` and the `client_id` are a combination of the App ID/GUID's with other stuff, but @Estro can explain it better than me, since I'm no SharePoint expert.

Interesting that you say that you had to manually debug the response, because an `SPException` should be thrown when the API returns an error.

Can you paste the JSON object with the error the API returned?

**Comment by dwhofer** [comment]
Closing this question since our MSP refuses to support configuring a trust with the Azure AD.

**Comment by quetzyg** [comment]
I'm reopening the issue because I'm interested in the error you described, since it didn't throw a `SPException` (apparently?).

Again, can you paste the JSON object that the API returned?

**Comment by dwhofer** [comment]
I do not have any idea how you get the resource or the client_id as formatted in your example.  Here are the provided values:

'resource'  => '00000000-0000-ffff-0000-000000000000/example.sharepoint.com@09g7c3b0-f0d4-416d-39a7-09671ab91f64',

'client_id' => '52848cad-bc13-4d69-a371-30deff17bb4d/example.com@09g7c3b0-f0d4-416d-39a7-09671ab91f64',

'secret'    => 'YzcZQ7N4lTeK5COin/nmNRG5kkL35gAW1scrum5mXVgE='

I understand perfectly well, how to get the client_id and secret.  I have no idea though, where the client_id prefix "52848cad-bc13-4d69-a371-30deff17bb4d/example.com@" comes from?   Likewise, I have no idea where to get the resource id comes from.  

Thanks.

**Comment by quetzyg** [comment]
When you opened the issue, you said:

> I used your debugging tips to set the json param to 'false' in the createFromAOP function in SPAccessToken.php. With this, I was able to see this detailed error: **"ACS90019: Unable to determine the tenant identifier from the request."**

What I'm interested in is the whole API response body you debugged, which contains the error you provided.

I'm assuming an `SPException` wasn't thrown, because you said you had to debug the response manually. That's what I'm interested in.

Also, from your last reply, are you saying that you used the dummy SharePoint credentials I have in the examples? I tried them and didn't get the error you reported.

**Comment by mauricionr** [comment]
I'm having the same problem to get the Access Token in my NodeJS App

"{\"error\":\"invalid_request\",\"error_description\":\"ACS90019: Unable to determine the tenant identifier from the request.\r\nTrace ID: 5c538fef-
b2f4-458f-b245-d8ee008ea68c\r\nCorrelation ID: 52aa08b0-3bc6-4850-85ef-c1d7d3f3fc91\r\nTimestamp: 2015-09-17 17:25:10Z\",\"error_codes\":[90019],\
"timestamp\":\"2015-09-17 17:25:10Z\",\"trace_id\":\"5c538fef-b2f4-458f-b245-d8ee008ea68c\",\"correlation_id\":\"52aa08b0-3bc6-4850-85ef-c1d7d3f3fc91\
"}"

```
//https://gist.github.com/demelziraptor/9039435 Python
//http://www.getcodesamples.com/src/A39B1460/F692912D  PHP
    req.session.sp_info = req.query;
    req.session.sp_oauth = req.body;
    var client_ID = "{{ClientID}}"    
    var appSecret = '{{AppSecret}}';
    var decoded = jwt.decode(req.session.sp_oauth.SPAppToken, appSecret)
    decoded.appctx = JSON.parse(decoded.appctx);
    var appctx = decoded.appctx;
    var options = {
        headers: {
            "Content-Type": "application/x-www-form-urlencoded"
        },
        form: {
            "grant_type": "refresh_token",
            "client_id": decoded['aud'].split('/')[0],
            "client_secret": appSecret,
            "refresh_token": encodeURI(decoded.refreshtoken),
            "resource": decoded['appctxsender'].split('@')[0] + '/' + decoded['aud'].split('/')[1].split('@')[0] + '@' + decoded['appctxsender'].split('@')[1]
        }
    };
    var callback = function (req, res, body) {
        console.log(JSON.stringify(body));
    }

    var r = request.post(appctx.SecurityTokenServiceUri, options, callback)

```

**Comment by quetzyg** [comment]
Come on @mauricionr, seriously? Just because you're using SharePoint, doesn't mean you have to put every problem here. This is an issue tracker for a **PHP** library that deals with SharePoint, not for NodeJS or SharePoint in general.

Get some sense, I mean, there's [plenty](http://sharepoint.stackexchange.com/) of [places](http://stackoverflow.com/) around for that.

PS: A sério, acorda prá vida.
