### ISSUE TITLE
Sharepoint, office 365

### ISSUE THREAD

**Issue by hhovind** [wearearchitect/sharepoint-oauth-app-client#7]
Is this supposed to work with sharepoint for office 365, or am I getting it wrong?

I believe I have provided the correct credentials, and  _$site->setSPAccessToken()_ does generate a token.

However, if I try to do anything like _$lists = SPList::getAll($site)_, or any other operation, I get this error:

WeAreArchitect\SharePoint\SPException: Access denied. You do not have permission to perform this action or access this resource.

**Comment by quetzyg** [comment]
Hi @hhovind,

That's a very good question. I haven't tested the lib with an Office 365 SP, so I can't confirm if it's supposed to work out of the box or not.

From the error message, it does seem to have support for it, being just a a permissions issue.

But I'll pass the ball to @Estro, to see what he says about this.

**Comment by Estro** [comment]
Hi @hhovind,

Yes it works on Office 365 SP. It's actually on-prem that it has not been tested on. It sounds like the issue is most likely related to the resource and client Id in your credentials. Make sure you have followed the credentials guide correctly:

https://github.com/wearearchitect/sharepoint-oauth-app-client/blob/master/docs/Credentials.md

You should also check that the SharePoint Hosted App that has been added to the site has the correct permissions set via the App manifest. More information can be found at the following link:

https://msdn.microsoft.com/en-us/library/office/fp142383.aspx

**Comment by Estro** [comment]
Also, are you trying to use a user or app only token? 

If using the App only policy, you need to add a 'AllowAppOnlyPolicy' attribute to the AppPermissionRequests node within the app manifest with a value of true.

**Comment by hhovind** [comment]
Thank you for your replies, @quetzyg and @Estro 

You were right, I was using App-only policy, and I had to add the AllowAppOnlyPolicy attribute.
It seems to be working perfectly now, thanks!

Also thanks for a great lib!

**Comment by quetzyg** [comment]
:+1: 
Nice to know it's working for you @hhovind.
